# FastAPI app settings on Google App Engine. This is required for Google Cloud deployment.
# This file is not used for the frontend Streamlit app during deployment.

runtime: python39

entrypoint: uvicorn app.main:app --host=0.0.0.0 --port=$PORT

env_variables:
  PRODUCTION_URL: 'https://elegant-tendril-245600.ue.r.appspot.com'
  RUNNING_IN_CLOUD: "true" # Set this to "false" if you are running locally